export const RIF_TOKEN_ADDRESS = {
  30 : process.env.REACT_APP_RIF_TOKEN_ADDRESS_MAINNET,
  31 : process.env.REACT_APP_RIF_TOKEN_ADDRESS_TESTNET
}

export const RSK_RPC_URL = {
  30 : process.env.REACT_APP_RSK_RPC_URL_MAINNET,
  31 : process.env.REACT_APP_RSK_RPC_URL_TESTNET
}

export const RSK_EXPLORER = {
  30 : process.env.REACT_APP_RSK_EXPLORER_MAINNET,
  31 : process.env.REACT_APP_RSK_EXPLORER_TESTNET
}